Apom_User/Apom_User/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apom_User.Controllers
{
    public class AboutController : BaseController
    {
        // GET: About
        public ActionResult Index()
        {
            ViewBag.page = Common.Constant.Page.about;
            return View();
        }
    }
}

Apom_User/Apom_User/Controllers/BugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Apom_User.Controllers
{
    public class BugController : BaseController
    {
        // GET: Bug
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Error400()
        {
            return View();
        }
        public ActionResult Error401()
        {
            return View();
        }
        public ActionResult Error403()
        {
            return View();
        }
        public ActionResult Error404()
        {
            return View();
        }
        public ActionResult Error500()
        {
            return View();
        }

        public ActionResult Maintenance()
        {
            return View();
        }
    }
}

Apom_User/Apom_User/Views/Bug/partial/_footprint.cshtml
<fieldset class="row py-2">
    <div class="input-group col-12">
        <input type="text" class="form-control form-control-xl input-xl border-grey border-lighten-1 " placeholder="Search..." aria-describedby="button-addon2">
        <span class="input-group-append" id="button-addon2">
            <button class="btn btn-secondary border-grey border-lighten-1" type="button"><i class="feather icon-search"></i></button>
        </span>
    </div>
</fieldset>
<div class="row py-2">
    <div class="col-12 col-sm-6 col-md-6 mb-1">
        <a href="@Url.Action("Index", "Home", new { area = "" })" class="btn btn-primary btn-block"><i class="feather icon-home"></i> @Resources.Common.home</a>
    </div>
    <div class="col-12 col-sm-6 col-md-6 mb-1">
        <a href="@Url.Action("Index", "About", new { area = "" })" class="btn btn-danger btn-block"><i class="fa fa-user-o"></i> @Resources.Common.about</a>
    </div>
</div>