Apom_User/Apom_User/Controllers/AnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Repositories.Models;
using Repositories.Models.Asset;
using Repositories.Models.Category;
using Repositories.Services.Asset;
using Repositories.Services.Category;

namespace Apom_User.Controllers
{
    public class AnalysisController : BaseController
    {
        // GET: Analysis
        [Route("/analysis_data")]
        public ActionResult Index()
        {
            Language();
            ViewBag.use_datatable = true;
            ViewBag.use_map = true;
            ViewBag.use_chart = true;
            //ViewBag.use_switch = true;
            //ViewBag.use_baseslider = true;
            ViewBag.page = Common.Constant.Page.data_analysis;

            //List<group_tree> lstGroupTree = groupLocalServiceUtil.Instance.buildGroupStationTree(Common.SessionContext.Language);

            List<province> lstProvince = provinceLocalServiceUtil.Instance.getAll(Common.SessionContext.Language);
            List<vnaqi_index_short> lstAQIIndexShort = vnaqiindexLocalServiceUtil.Instance.getInfoShort(Common.SessionContext.Language);

            analysis_model_view modelView = new analysis_model_view
            {
                Provinces = lstProvince,
                VNAQIIndex = lstAQIIndexShort
            };
            return View(modelView);
        }
    }
}

Apom_User/Apom_User/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Globalization;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace Apom_User.Controllers
{
    public class CommonController : Controller
    {
        // GET: Common
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChangeLanguage(string url, string culture)
        {
            if (!Common.Constant.WebConfig.LIST_LANGUAGE.Contains(culture)) culture = Common.Constant.LANGUAGE_DEFAULT;
            string urlRedirect = url;
            
            //// check authen
            //if (SessionContext.UserProfile == null) urlRedirect = "/Account/Login";
            //else
            //{
            //    // check: system have contain controller, action of url?
            //    Uri uri = new Uri(url);
            //    string localPath = uri.LocalPath;
            //    string[] localPaths = localPath.Split('/');

            //    bool bAuthen = false;
            //    // in case of: /GIS/MainMap || /Asset
            //    string controller = (String.IsNullOrEmpty(localPaths[localPaths.Length - 1]) ? "Home" : localPaths[localPaths.Length - 1]) + "Controller";
            //    string action = "Index"; // action default 
            //    if (Common.Constant.CONTROLLER_ACTION_ALL.ContainsKey(controller) && Common.Constant.CONTROLLER_ACTION_ALL[controller].Contains(action))
            //    {
            //        bAuthen = true;
            //    }
            //    else
            //    {
            //        // in case of: /Asset/Info
            //        controller = localPaths[localPaths.Length - 2] + "Controller";
            //        action = localPaths[localPaths.Length - 1];
            //        if (Common.Constant.CONTROLLER_ACTION_ALL.ContainsKey(controller) && Common.Constant.CONTROLLER_ACTION_ALL[controller].Contains(action))
            //        {
            //            bAuthen = true;
            //        }
            //    }
            //    if (!bAuthen) urlRedirect = "/Home";
            //}

            // create cookies language
            var languageCookie = new HttpCookie(Common.Constant.WebConfig.LANGUAGE, culture);
            languageCookie.Expires = DateTime.Now.AddDays(Common.Constant.WebConfig.COOKIE_TIMEOUT);

            HttpContext.Response.Cookies.Add(languageCookie);

            Common.SessionContext.Language = culture;

            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(culture);
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;
            //Thread.CurrentThread.CurrentUICulture = new CultureInfo(culture);

            return Redirect(urlRedirect);
        }
    }
}

Apom_User/Apom_User/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Apom_User.Common;
using Repositories.Models;
using Repositories.Models.Category;
using Repositories.Services.Category;

namespace Apom_User.Controllers
{
    public class DashboardController : BaseController
    {
        // GET: data_analysis
        public async Task<ActionResult> Index(string provinceId = "VNM.27_1")
        {
            Language();
            ViewBag.use_datatable = true;
            ViewBag.use_map = true;
            ViewBag.use_chart = true;
            ViewBag.page = Common.Constant.Page.data_analysis;

            List<map_scale> lstMapScale = await mapscaleLocalServiceUtil.Instance.getAllAsync();
            List<vnaqi_index_short> lstAQIIndexShort = await vnaqiindexLocalServiceUtil.Instance.getInfoShortAsync(Common.SessionContext.Language);
            List<province> lstProvince = await provinceLocalServiceUtil.Instance.getAllAsync(Common.SessionContext.Language);
            var cookies = Request.Cookies[Constant.WebConfig.COOKIE_URL] != null ? Request.Cookies[Constant.WebConfig.COOKIE_URL] : null;
            bool isAuthenticate = false, isVietNam = false;
            if (cookies != null)
            {
                isAuthenticate = cookies.Values["is_auth"] == "1" ? true : false;
                isVietNam = cookies.Values["is_vn"] == "1" ? true : false;
            }
            if (!isVietNam)
            {
                lstProvince = lstProvince.Where(x => x.province_id == provinceId).ToList();
            }

            analysis_model_view modelView = new analysis_model_view
            {
                Provinces = lstProvince,
                VNAQIIndex = lstAQIIndexShort,
                isAuthenticate= isAuthenticate,
                isVietNam= isVietNam
            };
            return View(modelView);
        }
    }
}

Apom_User/Apom_User/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using System.ComponentModel.DataAnnotations;

using Repositories.Models;
using Repositories.Models.Administrative;
using Repositories.Models.Archive;
using Repositories.Services.Administrative;
using Repositories.Services.Archive;

using Apom_User.Common;
using Common;
using System.Threading.Tasks;

namespace Apom_User.Controllers
{
    public class UserController : BaseAuthenController
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> UserInfo(string paraI, string time_request = null)
        {
            try
            {
                ViewBag.page = Common.Constant.Page.user_profile;
                long timeRegister = time_request == null ? SessionContext.UserProfile.time_request.Value : Convert.ToInt64(time_request);
                // convert parameter
                string emailAddress = "";
                try
                {
                    emailAddress = Libs.Utils.Encrypts.Decrypt(String.Concat(timeRegister, "_", Constant.WebConfig.KEYENDE), paraI);
                    if(time_request == null) SessionContext.UserProfile.time_request_old = timeRegister;
                }
                catch(Exception ex)
                {
                    timeRegister = SessionContext.UserProfile.time_request_old.Value;
                    emailAddress = Libs.Utils.Encrypts.Decrypt(String.Concat(timeRegister, "_", Constant.WebConfig.KEYENDE), paraI);
                }

                // header: start 
                var model = new user_info_view
                {
                    header = new Repositories.Models.header
                    {
                        root = new Repositories.Models.link_model
                        {
                            Title = Resources.Administrator.user_information,
                            link = "UserInfoUser"
                        },
                        lCate = new List<Repositories.Models.link_model>()
                    }
                };

                model.header.lCate.Add(new Repositories.Models.link_model
                {
                    Title = Resources.Administrator.user,
                    level = 1
                });

                var temModel = TempData["userProfile"];

                user _user = await userLocalServiceUtil.Instance.getUserbyEmailPwdAsync(emailAddress, null);
                if(_user == null) return RedirectToAction("Error400", "Bug");
                model.user = new user_info_model();
                object objTo = model.user;
                ReflectionObject.setValue(_user, ref objTo);
                List<user_role_view> lstUserRoleView = await userroleLocalServiceUtil.Instance.getAllUserRoleViewAsync(model.user.userid);
                model.user.role = lstUserRoleView;
                                
                //model.userGroups = new GroupUserLocalServiceUtil().getByUserId(model.User.vidagis_userid);
                //model.userRoles = new UserRoleLocalServiceUtil().getByUserId(model.User.vidagis_userid, Common.SessionContext.Organization.vidagis_organizationid);
                //model.User.vidagis_image = dlFileEntryLocalServiceUtil.getPath(model.User.vidagis_image);
                model.paraI = paraI;
                string avatar = "";
                try
                {
                    //avatar = DLFileEntryLocalServiceUtil.Instance.getPath(model.User.vidagis_image);
                }
                catch (Exception ex)
                {
                    String functionName = System.Reflection.MethodBase.GetCurrentMethod().Name.ToUpper();
                    Log.LOG4NET.Error("ERROR " + functionName + ": " + ex.Message);
                }

                //ViewBag.isUpdate = true;
                //ViewBag.isDelete = isAdd;
                ViewBag.use_datatable = true;
                //ViewBag.avatar = avatar;
                ViewBag.page = Common.Constant.Page.user_profile;
                Log.LOG4NET.Info("Info: " + model.user.displayname);
                ViewData["lError"] = TempData["lError"];

                if (String.IsNullOrEmpty(SessionContext.Theme))
                {
                    SessionContext.Theme = "";
                    return View("UserInfo1", model);
                }
                else if (SessionContext.Theme == Constant.Theme.STACK)
                {
                    SessionContext.Theme = Constant.Theme.STACK;
                    return View(model);
                }
                else return View("Index_Theme_No_Support");

            }
            catch (Exception ex)
            {
                String functionName = System.Reflection.MethodBase.GetCurrentMethod().Name.ToUpper();
                Log.LOG4NET.Error("ERROR " + functionName + ": " + ex.Message);
                return RedirectToAction("Error400", "Bug");
            }
        }

        [Apom_User.Common.ActionFilter.CustomIdentityActionFilter]
        public async Task<ActionResult> Account_Setting(string paraI, string t, string redirect = "")
        {
            try
            {
                long timeRegister = Convert.ToInt64(t);
                // convert parameter
                string emailAddress = Libs.Utils.Encrypts.Decrypt(String.Concat(timeRegister, "_", Constant.WebConfig.KEYENDE), paraI);
                
                // header: start 
                var model = new user_info_view
                {
                    header = new Repositories.Models.header
                    {
                        root = new Repositories.Models.link_model
                        {
                            Title = Resources.Administrator.user_information,
                            link = "UserInfoUser"
                        },
                        lCate = new List<Repositories.Models.link_model>()
                    }
                };

                model.header.lCate.Add(new Repositories.Models.link_model
                {
                    Title = Resources.Administrator.user,
                    level = 1
                });

                var temModel = TempData["userProfile"];

                user _user = await userLocalServiceUtil.Instance.getUserbyEmailPwdAsync(emailAddress, null);
                if(_user.userid == userLocalServiceUtil.Instance.SupperAdminDefault.userid)
                {
                    return RedirectToAction("Error403", "Bug");
                }
                model.user = new user_info_model();
                object objTo = model.user;
                ReflectionObject.setValue(_user, ref objTo);
                List<user_role_view> lstUserRoleView = await userroleLocalServiceUtil.Instance.getAllUserRoleViewAsync(model.user.userid);
                model.user.role = lstUserRoleView;

                //model.userGroups = new GroupUserLocalServiceUtil().getByUserId(model.User.vidagis_userid);
                //model.userRoles = new UserRoleLocalServiceUtil().getByUserId(model.User.vidagis_userid, Common.SessionContext.Organization.vidagis_organizationid);
                //model.User.vidagis_image = dlFileEntryLocalServiceUtil.getPath(model.User.vidagis_image);
                model.paraI = paraI;
                string avatar = "";
                try
                {
                    //avatar = DLFileEntryLocalServiceUtil.Instance.getPath(model.User.vidagis_image);
                }
                catch (Exception ex)
                {
                    String functionName = System.Reflection.MethodBase.GetCurrentMethod().Name.ToUpper();
                    Log.LOG4NET.Error("ERROR " + functionName + ": " + ex.Message);
                }

                //ViewBag.isUpdate = true;
                //ViewBag.isDelete = isAdd;
                //ViewBag.use_datatable = true;
                //ViewBag.avatar = avatar;
                Log.LOG4NET.Info("Info: " + model.user.displayname);
                ViewData["lError"] = TempData["lError"];
                return View(model);

            }
            catch (Exception ex)
            {
                String functionName = System.Reflection.MethodBase.GetCurrentMethod().Name.ToUpper();
                Log.LOG4NET.Error("ERROR " + functionName + ": " + ex.Message);
                return RedirectToAction("Error400", "Bug");
            }
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Apom_User.Common.ActionFilter.CustomIdentityActionFilter]
        public async Task<ActionResult> Account_Setting_Info()
        {
            this.Language();
            string userId = Request.Form["userid"];
            user _user = await userLocalServiceUtil.Instance.getUserAsync(userId);
            if (ModelState.IsValid)
            {
                string username = Request.Form["account-username"];
                //string email = Request.Form["account-email"];
                string firstname = Request.Form["account-firstname"];
                string middlename = Request.Form["account-middlename"];
                string lastname = Request.Form["account-lastname"];
                string bỉrthday = Request.Form["account-bỉthday"];
                string phonenumber = Request.Form["account-phonenumber"];
                string company = Request.Form["account-company"];
                string sex = Request.Form["account-sex"];
                string website = Request.Form["account-website"];

                bool isChangeAvatar = Request.Form["account-change-avatar"] == "1" ? true : false;

                _user.username = username;
                //_user.emailaddress = email;
                _user.firstname = firstname;
                _user.middlename = middlename;
                _user.lastname = lastname;
                _user.phonenumber = phonenumber;

Apom_User/Apom_User/Views/Shared/stack-admin/partial/_filter_data.cshtml
@using Repositories.Models.Category
@{
    List<province> lstProvince = Model != null ? Model as List<province> : new List<province>();
    string langId = Apom_User.Common.SessionContext.Language;
}

<style>
    .filter-data .dropdown select {
        color: black;
    }

    .dropdown {
        background-color: white;
    }

        .dropdown:hover {
            transition: var(--transition);
            background-color: var(--white-50);
        }

        .dropdown select {
            color: var(--white);
            padding-left: 16px;
            cursor: pointer;
        }

        .dropdown .filter-data-daterange {
            padding: 12px 16px 12px 16px;
            border-radius: var(--border-radius-D);
        }
</style>

<link rel="stylesheet" type="text/css" href="~/theme/app-assets/vendors/css/pickers/daterange/daterangepicker.css">
<script src="~/theme/app-assets/vendors/js/pickers/daterange/daterangepicker.js"></script>

@*<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>*@

<div class="filter-data">
    @if (lstProvince.Count > 0)
    {
        <div class="dropdown">
            @*<div class="icon">
                    <span class="font-icon-location"></span>
                </div>*@
            <select class="filter-data-province">
                @{
                    for (int i = 0; i < lstProvince.Count; i++)
                    {
                        province p = lstProvince[i];
                        string name = langId == "vi" ? p.name : p.name_en;
                        <option value="@p.province_id">@name</option>
                    }
                }
            </select>
        </div>

        <div class="dropdown">
            @*<div class="icon">
                    <span class="font-icon-location"></span>
                </div>*@
            <input type="text" name="daterange" class="filter-data-daterange" size="22" value="08/01/2022 - 08/20/2022" />
        </div>

        <div class="dropdown">
            @*<div class="icon">
                    <span class="font-icon-location"></span>
                </div>*@
            <select class="filter-data-aqi">
                <option value="aqi" selected="selected">AQI</option>
                <option value="pm25">PM 2.5</option>

            </select>
        </div>

        @*<div class="dropdown active">
                <span>Lọc dữ liệu</span>
                <div class="icon">
                    <span class="font-icon-arrow-right"></span>
                </div>
            </div>*@
    }
</div>

Apom_User/Apom_User/Views/Shared/stack-admin/partial/_footer_new.cshtml
@using Repositories.Models.Category
@{ 
    List<map_scale> lstMapScale = new List<map_scale>();
    //if (Model != null && Model.MapScale != null)
    //{
    //    lstMapScale = Model.MapScale;
    //}
    //else
    //{
    //}
}

Apom_User/Apom_User/Views/Shared/stack-admin/partial/_footer_new_mobile.cshtml
@using Repositories.Models.Category

Apom_User/Apom_User/Views/Shared/stack-admin/partial/_header.cshtml
@using Repositories.Extension
@using Repositories.Services.Administrative

@{ 
    bool isHavePermissionAdmin = userroleLocalServiceUtil.Instance.isAdmin(Apom_User.Common.SessionContext.UserProfile.userid);
}

<style>
    .brand-text {
        text-transform: capitalize;
    }
</style>
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-dark bg-primary navbar-shadow navbar-brand-center">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="feather icon-menu font-large-1"></i></a></li>
                <li class="nav-item">
                    <a class="navbar-brand">
                        @*<img class="brand-logo" alt="stack admin logo" src="../theme/app-assets/images/logo/stack-logo-light.png">*@
                        @*<img class="brand-logo" alt="stack admin logo" src="~/FileStore/img/logo/2451423.27.png">*@
                        @Html.Partial("/Views/Shared/stack-admin/partial/_logo.cshtml")
                        <h2 class="brand-text">@Resources.Administrator.user_managerment</h2>
                    </a>
                </li>
                <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="feather icon-menu"></i></a></li>
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon feather icon-maximize"></i></a></li>
                    <li class="nav-item nav-search">
                        <a class="nav-link nav-link-search" href="#"><i class="ficon feather icon-search"></i></a>
                        <div class="search-input">
                            <input class="input" type="text" placeholder="@Resources.Common.search..." tabindex="0" data-search="template-search">
                            <div class="search-input-close"><i class="feather icon-x"></i></div>
                            <ul class="search-list"></ul>
                        </div>
                    </li>
                </ul>
                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-language nav-item">
                        @if (Apom_User.Common.SessionContext.Language == Apom_User.Common.Constant.LANGUAGE_DEFAULT)
                        {
                            <a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="flag-icon flag-icon-vn"></i>
                                <span class="selected-language"></span>
                            </a>
                        }
                        else
                        {
                            <a class="dropdown-toggle nav-link" id="dropdown-flag" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="flag-icon flag-icon-gb"></i>
                                <span class="selected-language"></span>
                            </a>
                        }
                        <div class="dropdown-menu" aria-labelledby="dropdown-flag">
                            <a class="dropdown-item" href="@Url.Action("ChangeLanguage","Common",new{url= Request.Url.PathAndQuery,  culture="vi" ,area=""})">
                                <i class="flag-icon flag-icon-vn"></i> @Resources.Common.vietnamese
                            </a>
                            <a class="dropdown-item" href="@Url.Action("ChangeLanguage","Common",new{url= Request.Url.PathAndQuery,  culture="en" ,area=""})">
                                <i class="flag-icon flag-icon-gb"></i> @Resources.Common.english
                            </a>
                        </div>
                    </li>
                    <li class="dropdown dropdown-user nav-item">
                        @if (Apom_User.Common.SessionContext.UserProfile != null)
                        {
                            Apom_User.Common.SessionContext.UserProfile.time_request = DateTime.Now.Ticks;
                            <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                                <div class="avatar avatar-online">
                                    @if (string.IsNullOrEmpty(Apom_User.Common.SessionContext.UserProfile.image))
                                    {
                                        <img src="~/gui/imgs/unnamed.png" alt="avatar">
                                    }
                                    else
                                    {
                                        <img src="@Url.Action("GetFile", "FileTransfer", new { area = "" })?file_id=@Apom_User.Common.SessionContext.UserProfile.image" alt="avatar" />
                                    }
                                </div>
                                <span class="user-name">
                                    @Apom_User.Common.SessionContext.UserProfile.username
                                </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="@Url.Action("UserInfo", "User", new { paraI = Libs.Utils.Encrypts.Encrypt(String.Concat(Apom_User.Common.SessionContext.UserProfile.time_request.Value.ToString(), "_", Apom_User.Common.Constant.WebConfig.KEYENDE), Apom_User.Common.SessionContext.UserProfile.emailaddress), time_request = Apom_User.Common.SessionContext.UserProfile.time_request, redirect = Request.Url.PathAndQuery })">
                                    <i class="feather icon-user"></i>
                                    @Resources.Administrator.user_info
                                </a>

                                    @*@if (isHavePermissionAdmin)
                                    {
                                        <a class="dropdown-item" href="@Url.Action("UserList", "User", new { area = "" })">
                                            <i class="fa fa-cogs"></i>
                                            <span class="menu-title" data-i18n="Contacts">@Resources.Administrator.user_list</span>
                                        </a>
                                    }*@

                                    <a class="dropdown-item" href="javascript:document.getElementById('logoutForm').submit()">
                                        <i class="feather icon-power" style="float: left;"></i>
                                        @using (Html.BeginForm("LogOff", "Account", new { area = "", redirect = Request.Url.PathAndQuery }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                        {
                                            @Html.AntiForgeryToken()
                                        }
                                        @Resources.Administrator.logout
                                    </a>

                                    @*<div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="login-with-bg-image.html"><i class="feather icon-voicemail"></i>@Resources.Common.warning</a>*@
</div>
                        }
                        else
                        {
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <div class="avatar avatar-online"><img src="~/gui/imgs/unnamed.png" alt="avatar"></div><span class="user-name">@Resources.Common.user</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="@Url.Action("Login", "Account", new { area = "" })"><i class="feather icon-user"></i> @Resources.Common.login</a>
                            <a class="dropdown-item" href="@Url.Action("Register", "Account", new { area = "" })"><i class="fa fa-registered"></i> @Resources.Common.register</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="login-with-bg-image.html"><i class="feather icon-voicemail"></i>@Resources.Common.warning</a>
                        </div>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

Apom_User/Apom_User/Views/Shared/stack-admin/partial/_header_new.cshtml
@using Repositories.Extension
@using Repositories.Services.Administrative

Apom_User/Apom_User/Views/Shared/stack-admin/partial/_header_new_mobile.cshtml
@using Repositories.Extension
@using Repositories.Services.Administrative

Apom_User/Apom_User/Views/Shared/stack-admin/partial/_menu.cshtml
@using Repositories.Extension
@using Repositories.Services.Administrative
@{ 
    bool isHavePermissionAdmin = userroleLocalServiceUtil.Instance.isAdmin(Apom_User.Common.SessionContext.UserProfile.userid);
    string redirectURL = Request.Url.PathAndQuery;
}
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow menu-border" style="z-index: 1001;">
    <!-- main menu header-->
    <!-- include includes/menu-header-->
    <!-- / main menu header-->
    <!-- main menu content-->
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class="navigation-header">
                <span></span><i class="feather icon-minus" data-toggle="tooltip" data-placement="right" data-original-title="General"></i>
            </li>
            @*<li class="" nav-item">
                <a href="#" class="redirect"><i class="feather icon-home"></i><span class="menu-title" data-i18n="Email Application">@Resources.Common.home</span></a>
            </li>*@
			
			@if (isHavePermissionAdmin)
			{
				<li class="nav-item" >
					<a href="@Url.Action("UserList", "User", new { area = "", redirect = redirectURL })">
					<i class="fa fa-cogs"></i>
					<span class="menu-title" data-i18n="Contacts">@Resources.Administrator.user_list</span>
					</a>
				</li>
			}
			
            @*@if (Apom_User.Common.SessionContext.UserProfile != null)
            {
            <li class="" nav-item">
                <a href="@Url.Action("Index", "Analysis", new { area = "" })"><i class="feather icon-bar-chart"></i><span class="menu-title" data-i18n="Todo Application">@Resources.Common.data_analysis</span></a>
            </li>
            }
            <li class="" nav-item">
                <a href="#"><i class="fa fa-table"></i><span class="menu-title" data-i18n="Contacts">@Resources.Common.report_onkk</span></a>
            </li>*@
            
            @if (Apom_User.Common.SessionContext.UserProfile != null)
            {
            @*<li class="" nav-item">
                <a href="#l"><i class="fa fa-cogs"></i><span class="menu-title" data-i18n="Contacts">@Resources.Common.setting</span></a>
            </li>*@
            }
        </ul>
    </div>
    <!-- /main menu content-->
    <!-- main menu footer-->
    <!-- include includes/menu-footer-->
    <!-- main menu footer-->
</div>